---
- name: Deploy cw2-server image (non-root)
  hosts: production-server
  become: false
  tasks:

    - name: Delete existing cw2-server deployment and service if they exist
      shell: |
        kubectl delete deployment cw2-server --ignore-not-found
        kubectl delete service cw2-server --ignore-not-found
      args:
        executable: /bin/bash

    - name: Deploy cw2-server from DockerHub using passed image tag
      shell: |
        kubectl create deployment cw2-server --image={{ image_name }}
        kubectl expose deployment cw2-server --type=NodePort --port=8081
      args:
        executable: /bin/bash







