---
- name: Deploy cw2-server image  (non-root)
  hosts: k8s_nodes
  become: false
  tasks:

    - name: Delete existing cw2-server deployment and service if they exist
      shell: |
        kubectl delete deployment cw2-server --ignore-not-found
        kubectl delete service cw2-server --ignore-not-found
      args:
        executable: /bin/bash

    - name: Deploy cw2-server from DockerHub
      shell: |
        kubectl create deployment cw2-server --image=ssenkaaayi/cw2-server:1.0
        kubectl expose deployment cw2-server --type=NodePort --port=8081
      args:
        executable: /bin/bash






